### ISSUE TITLE
Inconsistent docs/overview/type_definitions.md

### ISSUE THREAD

**Issue by jasone** [skiplang/skip#15]
The prose mentions a `Users` interface, but no interfaces are declared, nor used.  The inconsistency is significant enough I can't figure out what point was intended.

**Comment by pikatchu** [comment]
Thanks for pointing that out!

Hopefully it is fixed now. 

https://github.com/skiplang/skip/commit/3f88974f6a0607fbff57b8833e658498a94b1a27
