### ISSUE TITLE
Need Help in getting started

### ISSUE THREAD

**Issue by Kolhar730** [skiplang/skip#18]
Hello Everyone!

I'm a student and am interested in learning more about Skip, about how it works and probably build something on top of this. I'm new around here so how can I still contribute to this and learn about how programming languages are built.

Danke!

**Comment by Pavlos1** [comment]
You should probably start by trying to build the project itself. Instructions are provided here: [Instructions for building with `cmake`](docs/developer/README-cmake.md).

Then you can try looking at some of the open issues, or just dive into the source and figure out how it all fits together. It might help to look into general/academic resources about compilers, garbage collection etc.

**Comment by pikatchu** [comment]
Thanks @Pavlos1, that's a better answer than what I would have written myself :-)
