### ISSUE TITLE
Docs:  different docker mount path at Getting Started part

### ISSUE THREAD

**Issue by objectisundefined** [skiplang/skip#45]
when install, at step 3 run the Skip docker image
```sh
# Replace <skip-dir> with the directory you created above
docker run -it --user skip --mount type=bind,source=<skip-dir>,target=/home/skip/app verlaguet/skip
```
the mount target is `/home/skip/app`

at step 6, write, compile and run the example.sk program
```sh
# From docker container shell
> cd /home/skip/apps
> ls # should show example.sk created above
> ../skip/run.sh example.sk
```
now the mount target is `/home/skip/apps`

**Comment by josephsavona** [comment]
Oops, looks like a typo (those should both be 'app' or both 'apps'). Care to submit a PR to fix?

**Comment by objectisundefined** [comment]
I have sumit a pr(https://github.com/skiplang/skip/pull/48) to fix it, but I can't connect to https://code.facebook.com/cla, would it matter?

**Comment by vjeux** [comment]
What's the issue with https://code.facebook.com/cla ? Is this blocked because it's part of facebook.com and your work place prevents people from accessing it?

Small docs contributions are fine without a CLA but it would be great if you could sign it going forward :) Thanks!
