### ISSUE TITLE
Github Template Files

### ISSUE THREAD

**Issue by koolamusic** [skiplang/skip#61]
This repository doesn't have some useful GitHub template files at the barest : 

- ISSUE TEMPLATE
- PULL REQUEST TEMPLATE 

which are templates that can assist contributors in communicating their intentions better, 
I would love to work on this :smile:

**Comment by pikatchu** [comment]
That's not necessarily a bad idea. Do you have a specific template in mind? What would you like to see in those?

**Comment by koolamusic** [comment]
something like this 
https://prnt.sc/lbgpp0

Then with detailed instructions about how to communicate a PR or ISSUE

**Comment by pikatchu** [comment]
Ok I see. I am busy right now, getting the first release with binaries ready. Do you want to help with that? If you send me a PR that would be awesome.

**Comment by koolamusic** [comment]
Ok I would
