### ISSUE TITLE
skip_server doesn't watch for changes in the list of files referenced by globs in skip.project.json

### ISSUE THREAD

**Issue by aorenste** [skiplang/skip#65]
Current problem as of commit b26a4e

If you have a skip.project.json which refers to globs of files ("foo/**") and you add or remove files then you need to restart the server to pick up the new files.

Example:
```
{
  "skipVersion": "1.0",
  "programUnits": {
    "test": {
      "sources": [
        "srcs/**",
      ],
      "kind": "Program",
    }
  }
}
```
Have a file `srcs/file1.sk` and run `sk check` to start the server and let it type-check.

Add a new file `srcs/file2.sk` and run `sk check`.  It doesn't notice that file2.sk now exists until you `sk restart`.

**Comment by pikatchu** [comment]
Ok, that's super strange.

There is this piece of logic that should detect a file change. You can find it in the sk script.
```
if [ -f "$skdir/skfiles" ]; then
    find "$root" -name "*.sk" > "$skdir/skfiles_new"

    if [ $(diff "$skdir/skfiles" "$skdir/skfiles_new") ]; then
	echo "Detected a file configuration change"
        restart
    fi
fi
```

This should detect that you added or removed a new sk file.

**Comment by aorenste** [comment]
Possibly related - Sometimes (but not every time) I get the following error:
```
$ sk check compiler/
.../bin/sk: line 218: [: too many arguments
```
Line 218 is the diff line from your comment.

**Comment by aorenste** [comment]
In particular - I was getting that error when I would expect it to detect a new file...

**Comment by pikatchu** [comment]
Humm. I just tested on my machine, I don't see any error :-(

How did you install sk?

I did, in the skip root dir:
$ ./prepare-release.sh 0.7 && cd skip-Linux-0.7 && ./install.sh path_to_skip_bin

**Comment by aorenste** [comment]
@edwinsmith's fix is correct - to test you need to add multiple files
Easiest fix is:
```
@@ -215,7 +215,8 @@
 if [ -f "$skdir/skfiles" ]; then
     find "$root" -name "*.sk" > "$skdir/skfiles_new"

-    if [ $(diff "$skdir/skfiles" "$skdir/skfiles_new") ]; then
+    diff -q "$skdir/skfiles" "$skdir/skfiles_new" > /dev/null
+    if [ $? -ne 0 ]; then
        echo "Detected a file configuration change"
        restart
     fi
