### ISSUE TITLE
[doc website]

### ISSUE THREAD

**Issue by s-pace** [skiplang/skip#67]
👋  skiplang team,

I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [Bootstrap](https://getbootstrap.com/), [ESLint](https://eslint.org/) or [Babel](https://babeljs.io/).

As Docusaurus user, you would [need to enable our search experience.](https://docusaurus.io/docs/en/search#docsNav)

Looking forward to have it? Just update your `siteConfig.js`.:
```
apiKey: '7d79ea7bb5fdb8d123b2ed2c40d781a5',
  indexName: 'skiplang',
```

Feel free to reach me out for any issue.

We do offer free search analytics regarding the usage of your search. Send us the email of the ppl to add docsearcg@algolia.com

**Comment by vjeux** [comment]
Thanks, added in https://github.com/skiplang/skip/commit/267d28970d31c5587c99dcfaf6cb2fa743024216

Whenever @pikatchu updates the website, it should be live!

**Comment by s-pace** [comment]
:wave: @pikatchu I have deployed it locally and the website has now a search, do you plan to update the website soon?

Let me know if I can help
