### ISSUE TITLE
High Performance JS Backend

### ISSUE THREAD

**Issue by peterhal** [skiplang/skip#70]
Chatted with @josephsavona about this the other day. 

Here's a plan which would result in a JS backend which had perf on par with hand written JS. Goals would be:
- No boxing of primitives(bool, string, most numerics)
- Inlining of most operations on primitives (!, +, -, *, …)
 
We would need to make some concessions:
- only possible in an environment where monkey patching JS primitives was tolerable
- No longer 100% compatibility between JSBE and NBE.
- Duplicating/special casing more stdlib code between JSBE and NBE.
 
Work plan would look like:
- Rename ‘Int’ to ‘Int64’ in stdlib, make ‘Int’ an alias for Int64 in NBE; make ‘Int’ an alias for Int32 in JSBE.
  - This will require code review of all Int code in stdlib. In particular bitwise operations, hashing, Int.Max/Min, divide, mod, which will need to be special cased for the JSBE.
- Char becomes a 16-bit Unicode code unit in JSBE.
- String becomes a sequence 16-bit Unicode code units in JSBE.
  - Requires code review and special casing of much of String and StringIterator.
- No boxing for primitives:
  - Monkey patch JS builtins with all Skip methods/constants
  - JSBE can now not box builtins safely
- Update JSBE code gen to inline most primitives now that primitives are no longer boxed.
 
The cool thing at this point is that primitives still behave like other Skip types. They may participate in traits and everything just works. Generic code which references primitives will dispatch through the monkey patched methods rather than inlined. Future work could also:
- Special case any generic code which is instantiated to primitives to make generics on primitives run just as fast as non-generic versions of code.
 
Dead code removal (aka tree shaking) would be pretty trivial. So there’d be no penalty for using a large library in a small application.
 
To improve the programming model we could additionally:
- Add a ‘dynamic’ or ‘object’ type to represent untyped JS objects
- Add typed wrappers for HTML DOM types
- Enable inline JS implementations of methods with an additional modifier on the method

**Comment by pikatchu** [comment]
Would the plan be to have SKIP work a little bit like ReasonML?

**Comment by peterhal** [comment]
Not sure what you mean by 'like ReasonML' specifically. They both compile a strongly typed language to high performance JS code. The difference would be that ReasonML prioritizes human readable JS, while that would not be a goal for skip.

**Comment by peterhal** [comment]
On second thought, making Int an alias for Int32 would likely be a better call than Float64.

**Comment by pikatchu** [comment]
Hey! Closing this since I killed the JS backend. This is purely due to a lack of time. I don't have the resources to maintain as much as we used to when we had a team.
